### ISSUE TITLE
Question: What is "id"?

### ISSUE THREAD

**Issue by dvisztempacct** [elastic/node-traceparent#1]
Seen here:

https://github.com/elastic/node-traceparent/blob/master/index.js#L8

and here:

https://github.com/elastic/node-traceparent/blob/master/index.js#L20

Does this correspond to W3's "span ID?"

Thanks!

**Comment by watson** [comment]
Yeah, it might be a little confusing. The `context.id` corresponds to the `parent-id ` in the spec. Now that you mention it, we should maybe consider refactoring that to make it less confusing. But here's the thoughts behind it:

By default, you're viewing this from the point of the sender service. That service wants to add a header to an outgoing http request where the outgoing http request span is set to be the parent from the point of view of the receiver.

So it generates a header like this:

```js
const header = `${version}-${traceId}-${id}-${flags}`
```

In `header`, the `id` part is its own span id. But the header is, of course, meant to be read by the receiver, in which case it will become the parent span id of the receiving span.

Then when the request is received, the receiver will first parse the header like so:

```js
const parent = TraceParent.fromString(header)
```

Notice that the variable name I've chosen to use is `parent`. This function call just parsed the header, and so `parent.id` will contain the span id of the parent span.

Now this new service probably wants to start a child span of the parent, so it does this:

```js
const child = parent.child()
```

On the `child` object, you now have `child.parentId`, which is equal to `parent.id`, but you also have a random new span id on `child.id`.

Does that make sense?

**Comment by dvisztempacct** [comment]
That makes perfect sense, thanks!
